### ISSUE TITLE
no module named diff_jpeg

### ISSUE THREAD

**Issue by sei-cabidi** [sail-sg/Agent-Smith#2]
Hi there, excellent code and paper! After following setup procedure, I get the following crash:
```
>>> accelerate launch --config_file accelerate_config.yaml optimize.py --border=$border --div=$div --unconstrained

Traceback (most recent call last):
  File "Agent-Smith/attack/optimize.py", line 14, in <module>
    from diff_jpeg import diff_jpeg_coding
ModuleNotFoundError: No module named 'diff_jpeg'
```

Edit: I believe that the fix is to simply ```pip install git+https://github.com/necla-ml/Diff-JPEG```

**Comment by guxm2021** [comment]
Thank you for your comments. I will update it on README.md.
